# -*- coding: utf-8 -*-
"""Colab 시작하기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import torch
import librosa
from transformers import Wav2Vec2Processor, Wav2Vec2ForSequenceClassification


# 환경 설정 및 모델 로드
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 저장된 모델 경로 및 5대 감정 라벨
MODEL_PATH = "./final_korean_emotion_model"
EMOTIONS = ["Happy", "Sad", "Angry", "Fearful", "Neutral"]

try:
    # 저장된 파인튜닝 체크포인트 로드 후 GPU 배치
    processor = Wav2Vec2Processor.from_pretrained(MODEL_PATH)
    model = Wav2Vec2ForSequenceClassification.from_pretrained(MODEL_PATH).to(device)
    model.eval()
except Exception as e:
    print(f"지정된 경로 '{MODEL_PATH}'에서 모델을 찾지 못했습니다. 실습 환경에 맞게 로컬 기본 가중치로 대체합니다.")
    from transformers import Wav2Vec2FeatureExtractor
    emotion_model_name = "kresnik/wav2vec2-large-xlsr-korean"
    processor = Wav2Vec2FeatureExtractor.from_pretrained(emotion_model_name)
    model = Wav2Vec2ForSequenceClassification.from_pretrained(emotion_model_name, num_labels=5).to(device)
    model.eval()


# 2. 핵심 파이프라인 함수 정의
def predict_emotion(audio_path):
    """ 16kHz 음성 주파수를 분석하여 감정 라벨과 최고 확률 점수(%)를 반환합니다. """
    # 음성 오디오 로드
    speech, sr = librosa.load(audio_path, sr=16000)

    # 전처리 및 GPU 텐서 변환
    inputs = processor(
        speech,
        sampling_rate=16000,
        return_tensors="pt",
        padding=True
    )
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # 추론 가동
    with torch.no_grad():
        logits = model(**inputs).logits

    probs = torch.softmax(logits, dim=-1)[0]
    pred_id = torch.argmax(probs).item()

    # 콘솔 시각화 아웃풋
    print(f"\nWav2Vec2 분석 결과 예측 감정: {EMOTIONS[pred_id]}")
    print("-" * 35)
    for i, emotion in enumerate(EMOTIONS):
        print(f" {emotion:<8}: {probs[i].item()*100:.2f}%")
    print("-" * 35)

    detected_emotion = EMOTIONS[pred_id]
    confidence_score = probs[pred_id].item() * 100

    return detected_emotion, confidence_score


def build_prompt(user_text, detected_emotion, score):

    # 감정에 따른 핵심 지침
    emotion_guidelines = {
        "Sad": (
            "말투: 절대 조언하지 말고, 짧게 끊어서 말하는 다정한 어조\n"
            "행동: 유저의 슬픔을 성급히 해결하려 들지 말고, 묵묵히 위로하고 안심시킬 것"
        ),
        "Angry": (
            "말투: 유저의 흥분에 휘둘리지 않는, 낮고 차분하며 단단하게 가라앉은 톤\n"
            "행동: 감정적 반박은 절대 금지하며, 유저가 억울해하는 원인과 서운함에만 집중할 것"
        ),
        "Fearful": (
            "말투: 불안을 가라앉혀주는 속도가 느리고 부드러운 안심의 어조\n"
            "행동: 유저를 절대 다그치지 말고, 이 공간이 100% 안전하다는 확신을 줄 것"
        ),
        "Happy": (
            "말투: 격식을 차리지 않고 진심으로 함께 신나하는 활기차고 밝은 톤\n"
            "행동: 유저의 성취나 기쁜 정서를 함께 축하하며 유대감(라포)을 극대화할 것"
        ),
        "Neutral": (
            "말투: 과장이나 꾸밈이 없는 담백하고 편안한 일상 대화 톤\n"
            "행동: 단답형 답변을 피하고, 자연스럽게 속마음을 열 수 있는 개방형 질문을 던질 것"
        )
    }

    current_guideline = emotion_guidelines.get(detected_emotion, emotion_guidelines["Neutral"])

    # Gemma 4 호환형 경량 시스템 템플릿 패키징
    system_prompt = f"""당신은 청소년 전문 심리상담사입니다. "유저님", "내담자" 같은 챗봇용 단어는 절대 쓰지 마세요.
현재 유저의 음성 감정은 {detected_emotion}({score:.1f}%)로 진단되었습니다.

[실시간 행동 방침]
{current_guideline}"""

    # 최종 Gemma 4 턴 마크업 조립
    integrated_prompt = f"""<start_of_turn>system
{system_prompt}<end_of_turn>
<start_of_turn>user
{user_text}<end_of_turn>
<start_of_turn>model"""

    return integrated_prompt


# 3. 통합 파이프라인 최종 가동 및 검증
AUDIO_FILE_PATH = "test_voice.wav"  # 코랩 파일 탭에 업로드한 내 음성 녹음 파일 이름

try:
    # 1. Wav2Vec2 음색 정서 분석 수행
    emotion, confidence = predict_emotion(AUDIO_FILE_PATH)

    # 2. Whisper STT 모델 등을 통해 수집된 실제 발화 내용 매핑
    sample_user_text = "오늘 그냥 다 때려치우고 싶고 너무 억울해요."

    # 3. 분석 결과와 텍스트를 결합하여 압축형 프롬프트 생성
    final_prompt = build_prompt(sample_user_text, emotion, confidence)


    print("[Final Prompt]")
    print("==================================================================")
    print(final_prompt)

except FileNotFoundError:
    print(f"\n경로에 '{AUDIO_FILE_PATH}' 파일이 존재하지 않습니다.")